name: Tinkernauts
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: The Home of Victoria Tinderwood
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7e895'
    - '#6c6448'
    - '#ff7fff'
    - '#000000'
    - '#ff00ff'
  brandStrength: 0.1875
  lightness: 0.6794047618750483
  saturation: 0.5808721049688756
  rhythmicContrast: 0.3015325756277889
purpose: []
